[package]
name = "chipper"
version = "0.2.0"
authors = ["Ali Graham <ali.graham@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
bitvec = "1"
clap = { version = "4", features = ["derive"]}
once_cell = "1.16"
rand = "0.8"
sdl2 = "0.35"
